import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import localFont from 'next/font/local'

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const vulf = localFont({
  src: [
    {
      path: '../../public/fonts/Vulf-Mono/VulfMonoDemo-Italic.otf',
      weight: '400'
    }
  ],
  variable: '--font-vulf'
})

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${vulf.variable} font-sans bg-gradient-to-br from-blue-500 via-purple-500 to-pink-400 bg-repeat bg-fixed`}>{children}</body>
    </html>
  );
}
